### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by briandannenmueller** [treygrainger/ai-powered-search#37]
When I issue the command "docker-compose down" everything appears to run fine until it comes time to install python packages for the notebooks service. At this point, I receive: "ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device". I don't think that my device lacks the memory or RAM. Any suggestions what might be causing this issue? Is there any chance you could include system requirements on the README as well?

**Comment by epugh** [comment]
try `docker system prune` and then re run ;-)

**Comment by briandannenmueller** [comment]
Thanks for getting back so quickly! So yes, I did try that (also had seen that on Stack Overflow) and there wasn't anything crowding up the memory. I tried running docker-compose down again with the same result -- it's getting hung up while running "RUN python -m pip install --upgrade pip &&   pip install -r requirements.txt"....we get to pandas and then it crashes. The system also has almost a Terabyte of memory, so I don't understand how it could run out of space.

**Comment by epugh** [comment]
if the error is about ram, not disk, then maybe you need to give Docker more resources?  I've had to do that for some complex setups.

**Comment by treygrainger** [comment]
@briandannenmueller I agree with @epugh - you probably need to go into your Docker settings and allocate more disk space. I don't think it's related to RAM, I think when pip was trying to pull dependencies that wasn't enough disk space available to install them.

Going to close this for now. Adding system requirements to the README is a good idea; will get that in place before the final review. They've changes a few times throughout writing the book due to the release of Mac M1s and some interesting side-effects for AMD vs. ARM64 architectures and evolving support. Will nail this down before publication.
