### ISSUE TITLE
Can't setup on Mac OS (Apple Chip)

### ISSUE THREAD

**Issue by lucacerone** [treygrainger/ai-powered-search#66]
When you run `docker-compose up` the environment setup fails because there are no images available for Mac OS.

```
docker-compose up                                                                  at  11:52:45
[+] Running 0/1
 ⠴ zookeeper Pulling                                                                                                                                            2.5s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by lucacerone** [comment]
Setting the image to 3.5.8 [here](https://github.com/treygrainger/ai-powered-search/blob/e1820ad7bab9b90f9f77217b760e6e0b31971bb1/docker/docker-compose.yml#L50) fixes the issue.

**Comment by treygrainger** [comment]
This is fixed on this pull request: https://github.com/treygrainger/ai-powered-search/pull/73

I plan to merge within the next few days; just fixing a few lingering dependency bugs.

**Comment by treygrainger** [comment]
Should be fixed in master now with the latest commit (docker/data-science/notebooks/ch5/1.open-information-extraction.ipynb). Required lots of library updates, plus replacing an old one entirely, so took a bit to sort through all of that.

If you have any additional issues, please let me know. Thanks!
